# ---------------------------------------------------------------------------- #
#                                  Voyager BOT                                 #
# ---------------------------------------------------------------------------- #
# This System is made by Voyager Systems, All Terms of Service applies to this 
# product. Distribution of this system outside of Voyager's Premises is considered
# as copy-right infringment, do not attempt to distribute or re-use  this product 
# or any denomination, or function, of it outside of the Voyager Systems unless
# authorized by the Voyager Lead Developer.

#! THIS PRODUCT IS NOT FOR SALE

# Terms: https://voyagersys.xyz/terms
# Privacy: https://voyagersys.xyz/privacy
 
# ------------------------------- BOT Settings: ------------------------------ #
# Here you can customize your bot's output and information.
# ---------------------------------------------------------------------------- #

bot_settings = {
    'token': '',                               # Input: DISCORD TOKEN
    'status': ''                               # Input: Text
}

# ------------------------------ Server Settings ----------------------------- #
# Here you can customize the servers that have access to use your server's database.
# ---------------------------------------------------------------------------- #

server_settings = {
    'MainServer': 0,                            # Input: SERVER ID
    'AllianceServers': [0]                       # Input: SERVER ID, Example: [1234, 5678, 9101112, 123]
}

# ------------------------------- Mile Settings ------------------------------ #
# Here you can insert your miles password generated by the Voyager Miles BOT.
# ---------------------------------------------------------------------------- #

mile_settings = {
    'Password': ''                              # Input: Main Server Password
}

# ---------------------------------------------------------------------------- #
# END OF CODE
# ---------------------------------------------------------------------------- #